SET SCHEMA JC;

DROP TABLE W_SETOSA;
DROP TABLE PARAM_SETOSA;

CREATE COLUMN TABLE W_SETOSA (
W1 DECIMAL(4,1),
W2 DECIMAL(4,1),
W3 DECIMAL(4,1),
W4 DECIMAL(4,1),
B DECIMAL(4,1)
);

CREATE COLUMN TABLE PARAM_SETOSA LIKE W_SETOSA;

INSERT INTO W_SETOSA VALUES (0,0,0,0,0);

INSERT INTO PARAM_SETOSA VALUES (0,0,0,0,0);

CALL "_SYS_BIC"."iris.iris_perceptron/train_setosa"(100, 0.02, 0.01);

CALL "_SYS_BIC"."iris.iris_perceptron/test_setosa"(6.3, 3.3, 4.7, 1, ?);